import React from 'react'
import './privacyy.css'
function Privacyy() {
  return (

    <div className='privacy'>
      <div className='heading'>
      <h1>PRIVACY POLICY</h1>

      </div>
      <div className='content'>
        <h3>1. Information Collection:</h3><p> We collect various types of user information to provide access to 
Electro5050, improve user experience, and communicate important updates. This includes but is 
not limited to email addresses, usernames, and game preferences.<br></br></p>
<h3>2. Use of Information:</h3><p> We use collected information to personalize your experience on 
Electro5050, optimize platform functionality, and communicate game-related updates and 
promotions.<br></br></p>
<h3>3. Information Sharing:</h3><p> We do not share your personal information with third parties for 
marketing purposes. However, we may share aggregated and anonymized data with advertisers, 
sponsors, and partners for analytical and promotional purposes.<br></br></p>
<h3>4. Data Security:</h3> <p>We take reasonable measures to protect your data from unauthorized access, 
alteration, or disclosure. While we strive to maintain the security of your information, no online 
transmission or storage system is completely secure.<br></br></p>
<h3>5. Cookies and Tracking:</h3> <p>Electro5050 may use cookies, web beacons, and similar technologies 
to enhance user experience, monitor traffic patterns, and gather information about your 
interactions with the platform.<br></br></p>
<p>i. What are cookies?<br></br>
A cookie is a piece of information in the form of a very small text file that is 
placed on an internet user's computer. It is generated by a web page server (which 
is basically the computer that operates the website) and can be used by that server 
whenever the user visits the site. A cookie can be thought of as an internet user's 
identification card, which tells a website when the user has returned. Cookies 
can't harm your computer and we don't store any personally identifiable 
information about you on any of our cookies.<br></br>
ii. Why do we use cookies?<br></br>
Electro5050 uses two types of cookies: cookies set by us and cookies set by third 
parties (i.e. other websites or services). Electro5050 cookies enable us to keep you 
signed in to your account throughout your visit and to tailor the information 
displayed on the site to your preferences.<br></br>
iii. How can I manage my cookies on electro5050?<br></br>
If you wish to stop accepting cookies, you can do so through the Privacy Settings 
option in your browser.<br></br>
iv. Server Protection Policy<br></br>
All servers have full encryption;<br></br>
All backups have encryption;<br></br>
Firewalls, VPN Access;<br></br>
Access to servers allowed only over VPN;<br></br>
All http/s services work over Cloudflare;<br></br>
Connections to nodes over VPN;<br></br>
SSH port forwarding tunnels;<br></br>
Services allowed only over VPN;<br></br>
Server have firewall and allowed only SSH portAlerts on critical services.
Data Breach Notification
When Electro5050 will be made aware of personal data breaches we will notify 
relevant users in accordance with GDPR timeframes.<br></br>
v. Data International Transfer<br></br>
We only disclose personal data to third parties where it is necessary to provide the 
high-quality service or in order to respond lawful requests from authorities.<br></br>
vi. Personal Data Protection Policy<br></br>
Electro5050’s mission is to keep your Data safe and for this matter we protect 
your data in various ways. We provide our customers with high security 
standards, such as encryption of data in motion over public networks, encryption 
of data in database, auditing standards, Distributed Denial of Service mitigations, 
and a Live Chat available on-site.<br></br></p>
<h3>6. Third-Party Links:</h3> <p>Electro5050 may contain links to third-party websites or applications. 
We are not responsible for the content, practices, or privacy policies of such third parties.<br></br></p>
<h3>7. Your Choices:</h3> <p>You have the right to access, correct, and delete your personal information on 
Electro5050. You can also choose to opt out of receiving certain communications.<br></br></p>
<h3>8. Changes to Policy:</h3><p> We reserve the right to update our Privacy Policy as necessary. Continued 
use of Electro5050 after changes implies your acceptance of the updated policy. Please review 
the policy periodically.<br></br></p>
<h3>9. Privacy Violation:</h3> <p>Any unauthorized disclosure, sharing, or misuse of user information, as 
outlined in our Privacy Policy, is considered a violation of our terms and conditions.<br></br></p>
<h3>10. Technical Issues:</h3><p>
Although we try to do our best, problems could occur now and then. Our team will do everything 
we could to solve your problems as soon as possible. To assist you quicker, If an error occurs, 
please provide the following information and mail to us or use Live support in the game.<br></br>
Username<br></br>
Date and time of the problem<br></br>
Game ID<br></br>
Screenshot of the error, if possible<br></br>
We really appreciate your help and the error report you provided because your information report 
could help us improve.<br></br></p>
<h3>11. Information From Third Party Social Media Service:</h3><p>
Electro5050 allows You to create an account and log in to use the Service through the following <br></br>
Third-party Social Media Services:<br></br>
• Google<br></br>
• Facebook<br></br>
• Telegram<br></br>
• Instagram<br></br>
If You decide to register through or otherwise grant us access to a Third-Party Social Media 
Service, We may collect Personal data that is already associated with Your Third-Party Social 
Media Service's account, such as Your name, Your email address, Your activities or Your 
contact list associated with that account.<br></br>
You may also have the option of sharing additional information with the Electro5050 through 
Your Third-Party Social Media Service's account. If You choose to provide such information and 
Personal Data, during registration or otherwise, You are giving Electro5050 permission to use, 
share, and store it in a manner consistent with this Privacy Policy.<br></br></p>
<h3>12. Delete Personal Data:</h3><p>
You can request to have your personal data deleted if Electro5050 no longer have a legal reason 
to continue to process or store it. Please note that this right is not guaranteed - in the sense that 
Electro5050 do not have the ability to comply with your request if it is subject to a legal 
obligation to store your data. You can request the deletion of your personal data by sending an 
email to [our support email here]<br></br></p>


      </div>
     
    </div>
  )
}

export default Privacyy